bars/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('new_app.urls'))
]

new_app/models.py
from django.db import models


class Planet(models.Model):
    class Meta:
        verbose_name = 'Планета'
        verbose_name_plural = 'Планеты'

    name = models.CharField('Наименование планеты', max_length=100, blank=False, null=False,)

    def __str__(self):
        return self.name

class Teacher(models.Model):
    class Meta:
        verbose_name = 'Джедай'
        verbose_name_plural = 'Джедаи'

    name = models.CharField('Имя джедая', max_length=100, blank=False, null=False,)
    planet = models.ForeignKey(Planet, verbose_name='Джедай планеты', related_name='teacher_planet', blank=True,
                               null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name


class Candidate(models.Model):
    class Meta:
        verbose_name = 'Кандидат'
        verbose_name_plural = 'Кандидаты'

    name = models.CharField('Имя кандидата', max_length=100, blank=False, null=False,)
    planet = models.ForeignKey(Planet, verbose_name='Кандидат планеты', related_name='candidate_planet', blank=True,
                               null=True, on_delete=models.SET_NULL)
    age = models.IntegerField('Возраст', blank=True, null=True)
    email = models.EmailField('Почта кандидата', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, verbose_name='Джедай планеты', related_name='teacher_cand', blank=True,
                               null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '%s, %s, %s' % (self.name, self.age, self.planet.name)


class Question(models.Model):
    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    question_name = models.CharField('Вопрос для кандидата', max_length=255, blank=False, null=False,)
    checked = models.BooleanField('Правильный ответ', default=True)

    def __str__(self):
        return '%s, %s' % (self.question_name, self.checked)


class Answer(models.Model):
    class Meta:
        verbose_name = 'Ответ кандидата'
        verbose_name_plural = 'Ответы кандидата'

    candidate = models.ForeignKey(Candidate, verbose_name='Ответ кандидата', related_name='candidate_answer', blank=True,
                               null=True, on_delete=models.SET_NULL)
    question = models.ForeignKey(Question, verbose_name='Вопрос для кандидата', related_name='candidate_question', blank=True,
                               null=True, on_delete=models.SET_NULL)
    answer = models.BooleanField('Ответ кандидата', default=True)

    def __str__(self):
        return '%s, %s' % (self.question.question_name, self.answer)


class Challenge(models.Model):
    class Meta:
        verbose_name = 'Испытание'
        verbose_name_plural = 'Испытания'

    position = models.PositiveSmallIntegerField('Порядковый номер', blank=False, null=False, default=0)
    orden = models.OneToOneField(Planet, on_delete=models.CASCADE)
    question = models.ManyToManyField(Question)

templates/add_candidate.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Добавить кандидата {% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

templates/add_challenge.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Испытания {% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

templates/added_candidate.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Добрый день! {% endblock %}
{% block content %}
<h1>Поздравляю! Вы ответили на вопросы</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Кандидаты - {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
<ul class="list-group">
  <li class="list-group-item"><a href="{% url 'home' %}">Начальная страница</a></li>
  <li class="list-group-item"><a href="{% url 'teacher-list' %}">Список джедаев</a></li>
  <li class="list-group-item"><a href="{% url 'teacher-new' %}">Список джедаев(более 1 кандидата)</a></li>
</ul>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block content %}{% endblock %}
</body>
</html>

templates/candidate_detail.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} {{ candidate }} {% endblock %}
{% block content %}
<h1>{{ candidate.name }}</h1>
<h2>{{ candidate.age }}</h2>
{% for answer in candidate.answer_set.all %}
<p>{{ answer.question.text }}<br>{{ answer.answer|yesno:"Yes,No" }}</p>
{% endfor%}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Главная страница {% endblock %}
{% block content %}
<a href="{% url 'add_candidate' %}">Кандидат</a><br>
<a href="{% url 'choose_teacher' %}">Учитель</a>
{% endblock %}

templates/list_teachers.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Список учащихся {% endblock %}
{% block content %}
<table class="table table-bordered table-dark">
    <thead>
    <tr>
        <td>Имя джедая</td>
        <td>Планета</td>
        <td>Кол-во учеников</td>
    </tr>
    </thead>
    <tbody>
    {% for t in teacher %}
    <tr>
        <td>{{ t.name }}</td>
        <td>{{ t.planet }}</td>
        <td>{{ t.kolvo }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/select_teachers.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Выбрать учителей {% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
{% endblock %}

templates/teacher_candidates.html
{% extends 'base.html' %}
{% block title %} {{ block.main }} Кандидаты {% endblock %}
{% block content %}
  {% for candidate in candidates %}
    <p><a href="{% url 'candidate' candidate_id=candidate.id teach_id=teach_id %}">{{ candidate.name }}</a></p>

  {% endfor %}
  {% if candidates.count == 0 %}
    <p>Нет кандидатов! </p>
  {% endif %}
{% endblock %}